recipes_website-main/apps/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/<str:username>/', views.user_profile, name='profile'),
    path('change-profile/', views.edit_profile, name='edit_profile'),
]

recipes_website-main/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('', include('apps.recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

recipes_website-main/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='static/profile_pics/', blank=True)
    bio = models.TextField(blank=True)
    instagram_url = models.URLField(max_length=255, blank=True, null=True)
    telegram_url = models.CharField(max_length=255, blank=True, null=True)

recipes_website-main/apps/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from apps.user.models import User


class ProfileChangeForm(forms.ModelForm):
    instagram_url = forms.URLField(required=False, widget=forms.URLInput(
        attrs={'placeholder': 'https://www.instagram.com/yourusername'}))
    telegram_url = forms.URLField(required=False,
                                  widget=forms.URLInput(attrs={'placeholder': 'https://t.me/yourusername'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'bio', 'profile_picture', 'instagram_url', 'telegram_url')
        widgets = {
            'username': forms.TextInput(attrs={'id': 'id_username'}),
            'email': forms.EmailInput(attrs={'id': 'id_email'}),
            'bio': forms.Textarea(attrs={'id': 'id_description'}),
            'profile_picture': forms.FileInput(attrs={'id': 'id_avatar', 'onchange': 'previewFile()'}),
        }

    def clean_instagram_url(self):
        instagram_url = self.cleaned_data.get('instagram_url', '')
        if instagram_url and not instagram_url.startswith('https://www.instagram.com/'):
            raise ValidationError("Посилання на Інстаграм повинно починатися з https://www.instagram.com/")
        return instagram_url

    def clean_telegram_username(self):
        telegram_url = self.cleaned_data.get('telegram_url', '')
        if telegram_url and not telegram_url.startswith('https://t.me/'):
            raise ValidationError("Посилання на Телеграм повинно починатися з https://t.me/")
        return telegram_url


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('username', 'email', 'password1', 'password2')

    def clean_email_or_username(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Дана електронна пошта вже використовується")
        elif User.objects.filter(username=username).exists():
            raise forms.ValidationError("Даний логін вже зайнятий")
        return email, username

recipes_website-main/apps/user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import CustomUserCreationForm
from apps.user.forms import ProfileChangeForm
from apps.user.models import User
from apps.recipes.models import Recipe, Favorite, Like


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'user/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'user/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home')


def user_profile(request, username):
    user = User.objects.get(username=username)
    recipes = Recipe.objects.filter(user=user.id).all()
    recipes_count = recipes.count()
    favorites_count = Favorite.objects.filter(recipe__user=user).count()
    likes_count = Like.objects.filter(recipe__user=user).count()
    statistic = {
        'recipes_count': recipes_count,
        'favorites_count': favorites_count,
        'likes_count': likes_count,
    }

    return render(request, 'user/profile.html', {'user': user, 'recipes': recipes, 'statistic': statistic})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated!')
            user = User.objects.get(username=request.user.username)
            recipes = Recipe.objects.filter(user=user.id).all()
            recipes_count = recipes.count()
            favorites_count = Favorite.objects.filter(recipe__user=user).count()
            likes_count = Like.objects.filter(recipe__user=user).count()
            statistic = {
                'recipes_count': recipes_count,
                'favorites_count': favorites_count,
                'likes_count': likes_count,
            }
            return render(request, 'user/profile.html', {'user': user, 'recipes': recipes, 'statistic': statistic})
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = ProfileChangeForm(instance=request.user)
    return render(request, 'user/edit_profile.html', {'form': form})

recipes_website-main/templates/user/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div style="max-width:420px;">
                <form action="{% url 'edit_profile' %}" class="bg-white border py-4 px-5" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="text-center mb-3">
                        {% if user.profile_picture and user.profile_picture.url %}
                            <img src="{{ user.profile_picture.url }}" alt="Profile Picture" class="img-fluid rounded-circle mb-3" width="100">
                        {% else %}
                            <img src="{% static 'no_image.png' %}" alt="Default Avatar" class="img-fluid rounded-circle mb-3" width="100">
                        {% endif %}
                        <h2>Зміна профілю</h2>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_avatar">Аватарка:</label>
                        {{ form.profile_picture }}
                        {% if form.profile_picture.errors %}
                            <div class="alert alert-danger">{{ form.profile_picture.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="id_username">Ім'я користувача:</label>
                        <input type="text" name="username" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username" placeholder="Логін" required value="{{ form.username.value|default_if_none:'' }}">
                        {% for error in form.username.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="id_email">Електронна пошта:</label>
                        <input type="email" name="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email" placeholder="Електронна пошта" required value="{{ form.email.value|default_if_none:'' }}">
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="id_bio">Опис:</label>
                        <textarea name="bio" id="id_bio" class="form-control {% if form.bio.errors %}is-invalid{% endif %}" rows="3">{{ form.bio.value|default_if_none:'' }}</textarea>
                        {% for error in form.bio.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="id_instagram_url"><i class="fab fa-instagram fa-lg me-2" style="color: #ac2bac;"></i>Instagram:</label>
                        <input type="text" name="instagram_url" class="form-control {% if form.instagram_url.errors %}is-invalid{% endif %}" id="id_instagram_url" placeholder="Instagram URL" value="{{ form.instagram_url.value|default_if_none:'' }}">
                        {% for error in form.instagram_url.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="id_telegram_url"><i class="fab fa-telegram fa-lg me-2" style="color: #55acee;"></i>Telegram:</label>
                        <input type="text" name="telegram_url" class="form-control {% if form.telegram_url.errors %}is-invalid{% endif %}" id="id_telegram_url" placeholder="Telegram Url" value="{{ form.telegram_url.value|default_if_none:'' }}">
                        {% for error in form.telegram_url.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2">
                        <button class="btn btn-dark bg-gradient fw-bold w-100 bg-gradient" type="submit">Зберегти</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

recipes_website-main/templates/user/login.html
{% include 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<section class="py-5">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div style="max-width:420px;">
                <form action="{% url 'login' %}" class="bg-white border py-4 px-5" method="post">
                    {% csrf_token %}
                    <div class="text-center mb-3">
                        <a href="{% url 'home' %}">
                            <img src="https://assets.materialup.com/uploads/d2feb47f-3d3c-4b05-8673-a2886e5f6aca/preview"

                                 alt="Logo" width="70"
                                 class="d-inline-block align-text-top mb-2">
                        </a>
                        <p class="text-muted fw-bold mt-2">
                            Війдіть, щоб підтвердити акаунт.
                        </p>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="form-floating mb-3">
                        {% if form.username.errors %}
                            <div class="alert alert-danger">{{ form.username.errors }}</div>
                        {% endif %}
                        <input type="text" name="username"
                               class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="username"
                               placeholder="Username" required>
                        <label for="username">Логін</label>
                    </div>
                    <div class="form-floating mb-3">
                        {% if form.password.errors %}
                            <div class="alert alert-danger">{{ form.password.errors }}</div>
                        {% endif %}
                        <input type="password" name="password"
                               class="form-control {% if form.password.errors %}is-invalid{% endif %}" id="password"
                               placeholder="Password" required>
                        <label for="password">Пароль</label>
                    </div>
                    <div class="mb-2">
                        <button class="btn btn-dark bg-gradient fw-bold w-100 bg-gradient" type="submit">Війти</button>
                    </div>
                </form>
                <div class="bg-white py-4 px-5 text-center border mt-4">
                    <p class="m-0">
                        Не маєте акаунту? <a href="{% url 'register' %}">Зареєструватися</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

recipes_website-main/templates/user/profile.html
{% include 'upper_part.html' %}
{% include 'cart.html' %}
{% load static %}
<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto">
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover position-relative">
                <div class="d-flex justify-content-center align-items-start stats-container mb-4"
                     style="position: absolute; font-size: 200%; left: 250px; height: auto; margin-top: 5%;">
                    <div class="stats-container-inner">
                        <div class="stats me-4">
                            <h6 class="mb-0">Рецептів</h6>
                            <span>{{ statistic.recipes_count }}</span>
                        </div>
                        <div class="social-links"
                             style="margin-top: 25%;">
                            {% if user.instagram_url %}
                                <a href="{{ user.instagram_url }}" target="_blank" title="Instagram"
                                   class="social-link-text">
                                    <i class="fab fa-instagram" style="color: #ac2bac;"></i> Instagram
                                </a>
                            {% endif %}
                            {% if user.telegram_url %}
                                <a href="https://t.me/{{ user.telegram_url }}" target="_blank" title="Telegram"
                                   class="social-link-text">
                                    <i class="fab fa-telegram" style="color: #55acee;"></i> Telegram
                                </a>
                            {% endif %}
                        </div>

                    </div>
                    <div class="stats me-4">
                        <h6 class="mb-0">Вподобань</h6>
                        <span>{{ statistic.favorites_count }}</span>
                    </div>
                    <div class="stats me-4">
                        <h6 class="mb-0">Обрані</h6>
                        <span>{{ statistic.likes_count }}</span>
                    </div>
                </div>
                <div class="profile-section d-flex align-items-center">
                    <div class="avatar mb-3">
                        {% if user.profile_picture %}
                            <img src="{{ user.profile_picture.url }}" alt="..." class="img-thumbnail rounded-circle">
                        {% else %}
                            <img src="{% static 'no_image.png' %}" alt="..." class="img-thumbnail rounded-circle">
                        {% endif %}
                    </div>
                </div>
                <div class="media align-items-end profile-head">
                    <div class="media-body mb-5 text-black">
                        <h4 class="mt-0 mb-0">@{{ user.username }}</h4>
                        {% if request.user.is_authenticated and request.user == user %}
                            <a href="{% url 'edit_profile' %}" class="btn btn-outline-dark btn-sm mt-2">Змінити
                                профіль</a>
                        {% endif %}
                    </div>
                </div>

            </div>
            {% if request.user.bio %}
                <div class="px-4 py-3"><h5 class="mb-2">Про себе</h5>
                    <div class="p-4 rounded">
                        <p class="font-italic mb-0">{{ user.bio }}</p>
                    </div>
                </div>
            {% endif %}
            <div class="recipes-section px-4 py-3">
                <h5>Опубліковані рецепти</h5>
                {% if recipes %}
                    <div class="row">
                        {% for recipe in recipes|slice:":3" %}
                            <div class="col-md-4 mb-3">
                                <div class="card recipe-card">
                                    {% if recipe.image %}
                                        <img src="{{ recipe.image.url }}" class="card-img-top recipe-image"
                                             alt="{{ recipe.title }}">
                                    {% else %}
                                        <div class="recipe-profile-image-placeholder">
                                            <span>Немає зображення</span>
                                        </div>
                                    {% endif %}
                                    <div class="card-body">
                                        <h6 class="card-title">{{ recipe.title }}</h6>
                                        <a href="{% url 'recipe_detail' recipe.id %}" class="btn btn-dark bg-gradient">Детальніше</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    <a href="{% url 'user_recipes' user.username %}" class="btn btn-outline-dark">Побачити всі</a>
                {% else %}
                    <p>Рецептів немає.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

recipes_website-main/templates/user/register.html
{% include 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Реєстрація</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<section class="py-5">
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div style="max-width:420px;">
                <form action="{% url 'register' %}" class="bg-white border py-4 px-5" method="post">
                    {% csrf_token %}
                    <div class="text-center mb-3">
                        <a href="{% url 'home' %}">
                            <img src="https://assets.materialup.com/uploads/d2feb47f-3d3c-4b05-8673-a2886e5f6aca/preview"

                                 alt="Logo" width="70"
                                 class="d-inline-block align-text-top mb-2">
                        </a>
                        <p class="text-muted fw-bold mt-2">
                            Зареєструйтесь, щоб почати користуватися.
                        </p>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <!-- Логін -->
                    <div class="form-floating mb-3">
                        <input type="text" name="username" id="id_username"
                               class="form-control{% if form.username.errors %} is-invalid{% endif %}"
                               placeholder="Логін" required value="{{ form.username.value|default_if_none:'' }}">
                        <label for="id_username">Логін</label>
                        {% for error in form.username.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <!-- Електронна пошта -->
                    <div class="form-floating mb-3">
                        <input type="email" name="email" id="id_email"
                               class="form-control{% if form.email.errors %} is-invalid{% endif %}"
                               placeholder="Електронна пошта" required
                               value="{{ form.email.value|default_if_none:'' }}">
                        <label for="id_email">Електронна пошта</label>
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <!-- Пароль -->
                    <div class="form-floating mb-3">
                        <input type="password" name="password1" id="id_password1"
                               class="form-control{% if form.password1.errors %} is-invalid{% endif %}"
                               placeholder="Пароль" required>
                        <label for="id_password1">Пароль</label>
                        {% for error in form.password1.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <!-- Повторіть пароль -->
                    <div class="form-floating mb-3">
                        <input type="password" name="password2" id="id_password2"
                               class="form-control{% if form.password2.errors %} is-invalid{% endif %}"
                               placeholder="Повторіть пароль" required>
                        <label for="id_password2">Повторіть пароль</label>
                        {% for error in form.password2.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2">
                        <button class="btn btn-dark bg-gradient fw-bold w-100 bg-gradient" type="submit">Зареєструватися</button>
                    </div>
                </form>
                <div class="bg-white py-4 px-5 text-center border mt-4">
                    <p class="m-0">
                        Вже маєте акаунт? <a href="{% url 'login' %}">Війти</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>